### ISSUE TITLE
no images loading

### ISSUE THREAD

**Issue by ausheikh** [delightedCrow/WallberryTheme#21]
images dont load, bottom right corner just says loading background photo, my config is:
{
			module: "WallberryTheme",
			position: "fullscreen_below", // Required Position
			config: {
				unsplashAccessKey: "XXXX", // REQUIRED
				collections: "219941", // optional - leave empty for a random photo
				updateInterval: 600000,
				orientation: "landscape"
    				}
  		},

**Comment by delightedCrow** [comment]
Are you getting any errors in the dev console log? (you can open MM with electron's dev tools enabled with the command `npm start dev`)

**Comment by ausheikh** [comment]
I dont see anything obvious when i start the console, I have other modules that work fine connecting to the internet
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-04-23 08:03:27.581] [LOG]    Starting MagicMirror: v2.11.0
[2020-04-23 08:03:27.670] [LOG]    Loading config ...
[2020-04-23 08:03:27.702] [LOG]    Loading module helpers ...
[2020-04-23 08:03:27.714] [LOG]    No helper found for module: alert.
[2020-04-23 08:03:28.121] [LOG]    Initializing new module helper ...
[2020-04-23 08:03:28.125] [LOG]    Module helper loaded: updatenotification
[2020-04-23 08:03:30.619] [LOG]    Initializing new module helper ...
[2020-04-23 08:03:30.621] [LOG]    Module helper loaded: calendar
[2020-04-23 08:03:30.624] [LOG]    No helper found for module: compliments.
[2020-04-23 08:03:30.627] [LOG]    No helper found for module: currentweather.
[2020-04-23 08:03:30.630] [LOG]    No helper found for module: weatherforecast.
[2020-04-23 08:03:30.807] [LOG]    Initializing new module helper ...
[2020-04-23 08:03:30.812] [LOG]    Module helper loaded: newsfeed
[2020-04-23 08:03:30.821] [LOG]    No helper found for module: MMM-PlexNowPlaying.
[2020-04-23 08:03:33.707] [LOG]    Initializing new module helper ...
[2020-04-23 08:03:33.712] [LOG]    Module helper loaded: MMM-DailyDilbert
[2020-04-23 08:03:33.732] [LOG]    Initializing new module helper ...
[2020-04-23 08:03:33.735] [LOG]    Module helper loaded: WallberryTheme
[2020-04-23 08:03:33.739] [LOG]    No helper found for module: WB-clock.
[2020-04-23 08:03:33.742] [LOG]    All module helpers loaded.
[2020-04-23 08:03:35.208] [LOG]    Starting server on port 8080 ...
[2020-04-23 08:03:35.386] [LOG]    Server started ...
[2020-04-23 08:03:35.392] [LOG]    Connecting socket for: updatenotification
[2020-04-23 08:03:35.398] [LOG]    Connecting socket for: calendar
[2020-04-23 08:03:35.403] [LOG]    Starting node helper for: calendar
[2020-04-23 08:03:35.409] [LOG]    Connecting socket for: newsfeed
[2020-04-23 08:03:35.415] [LOG]    Starting module: newsfeed
[2020-04-23 08:03:35.420] [LOG]    Connecting socket for: MMM-DailyDilbert
[2020-04-23 08:03:35.424] [LOG]    Starting node helper: MMM-DailyDilbert
[2020-04-23 08:03:35.427] [LOG]    Connecting socket for: WallberryTheme
[2020-04-23 08:03:35.430] [LOG]    Starting module helper: WallberryTheme
[2020-04-23 08:03:35.432] [LOG]    Sockets connected & modules started ...
[2020-04-23 08:03:37.001] [LOG]    Whoops! There was an uncaught exception...
[2020-04-23 08:03:37.006] [ERROR]  Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1413:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
[2020-04-23 08:03:37.063] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-04-23 08:03:37.068] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-04-23 08:03:37.094] [LOG]    Launching application.

**Comment by ausheikh** [comment]
Rebooted the devices and its working now
